---
title: "Exploring turbidity fluctuations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{turbidity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This is an example workflow of how to perform basic turbidity analysis with `loadflux` package and `tidyverse` ecosystem.

```{r setup, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(loadflux)
```

### Hydrological Events
First, we need to demarcate hydrological events

```{r events, out.width = "90%", fig.align='center'}
data(djanturb)
df <- hydro_events(dataframe = djanturb,
                   q = discharge,
                   datetime = time,
                   window = 21)

df %>% 
  event_plot(q = discharge,
             datetime = time,
             he = he,
             ssc = ntu,
             y2label = "Turbidity")

```

### Turbidity Index
Then we can calculate Turbidity Index `TI` for every hydrological event

```{r ti_index}

TI_index <- df %>% 
  group_by(he) %>% 
  nest() %>% 
  mutate(
    TI = vapply(data, function(x) TI(x, ntu, time), numeric(1))
  ) %>% 
  select(-data) %>% 
  ungroup()

TI_index

```
